### ISSUE TITLE
Load failed due to missing dependencies.

### ISSUE THREAD

**Issue by ArtiOJ** [mikatomik/Godot-4-Overgrown-Subway-Demo#1]
When I try to open this in Godot, I get the error in the title. I am not sure if this is because I am dumb and doing something wrong, but I am relatively certain I am not. The dependencies I am apparently missing are as follows: 

`res://subway/subway.blend` `res://props/cinder_blocks/cinder_blocks.blend` `res://props/barrel/barrel.tscn` `res://props/barrel/barrel_no_fire.tscn` `res://props/dirt_chunks/dirt_chunk.blend` `res://props/trash/trash.blend` `res://props/trash_can/trashcan.blend` `res://props/cork_board/corkboard.tscn` `res://outside_walls/outside_walls.tscn`

Again, I do not know why this is happening, but the same thing happens when I get it from the GitHub and from Godot's asset library projects tab.

**Comment by mikatomik** [comment]
Hey there. It looks like you do not have blend file support enabled. It is required to load those files. If you’re unsure how to do that, there is a link to the documentation that shows how to do this in the README file that comes with the git repo. :)

**Comment by GeorgeS2019** [comment]
Feedback, I git clone, not a good idea, need to download and make sure blender support is setup. Then it is fine

**Comment by mikatomik** [comment]
Yeah, it seems to be getting a few people. Part of the purpose of the demo was to show off the blender workflow, despite mentioning that in the README and on the asset library description, people still miss it. I'm wondering if there's a better way to failsafe this.

**Comment by GeorgeS2019** [comment]
It states blender 3.0.x.  Actually is > 3.0. e.g. 3.4

The Readme needs to link to not just blender but the subsection on how to setup blender in both editor and project menu

**Comment by mikatomik** [comment]
> The Readme needs to link to not just blender but the subsection on how to setup blender in both editor and project menu

The first bullet point under "How to use" links directly to Godot's documentation on how to set up support and enable it.
