### ISSUE TITLE
Unable to load rocks, but loops over other blends/scenes

### ISSUE THREAD

**Issue by garyritchie** [mikatomik/Godot-4-Overgrown-Subway-Demo#3]
Godot 4.0.3, Blender 3.5.1, on Ubuntu 22.04.2 with NVIDIA 525.116.04

Custom Blender path set in editor prefs as instructed. When loading scene Godot complains that it can't find rocks. F5 briefly opens playback window, but closes without additional error.

```log
Godot Engine v4.0.3.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started ---
  Cannot open file 'res://.godot/imported/outside_walls.blend-7e82b051a85d4f020e62544f5e59a306.scn'.
  Cannot open file 'res://.godot/imported/barrel.blend-73b291ff83112dcbbe7f021ce527d421.scn'.
  Cannot open file 'res://.godot/imported/cinder_blocks.blend-36614fbeeb7deeb2cfae935fa485e709.scn'.
  Cannot open file 'res://.godot/imported/corkboard.blend-e9ce2297f6d6d043c693e7223d13d1e4.scn'.
  Cannot open file 'res://.godot/imported/dirt_chunk.blend-7a3134bdab72468ff75aa9eb5a2868ce.scn'.
  Cannot open file 'res://.godot/imported/rocks.blend-98ef93dd145059a2bcdc7f8a6211eb83.scn'.
  Cannot open file 'res://.godot/imported/trash.blend-f7347673a6ecd237b883c9be4069183e.scn'.
  Cannot open file 'res://.godot/imported/trashcan.blend-487553615b1d4031d3d47fc743683076.scn'.
  Cannot open file 'res://.godot/imported/subway.blend-4fcf556f659b45d9abf5d0283981d835.scn'.
  modules/gltf/gltf_document.cpp:7431 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://outside_walls/outside_walls.blend'.
  modules/gltf/gltf_document.cpp:7431 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://props/barrel/barrel.blend'.
  modules/gltf/gltf_document.cpp:7431 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://props/cinder_blocks/cinder_blocks.blend'.
  modules/gltf/gltf_document.cpp:7431 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://props/cork_board/corkboard.blend'.
  modules/gltf/gltf_document.cpp:7431 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://props/dirt_chunks/dirt_chunk.blend'.
  modules/gltf/gltf_document.cpp:7431 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://props/rocks/rocks.blend'.
  modules/gltf/gltf_document.cpp:7431 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://props/trash/trash.blend'.
  modules/gltf/gltf_document.cpp:7431 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://props/trash_can/trashcan.blend'.
  modules/gltf/gltf_document.cpp:7431 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://subway/subway.blend'.
  Cannot open file 'res://.godot/imported/rocks.blend-98ef93dd145059a2bcdc7f8a6211eb83.scn'.
  Failed loading resource: res://.godot/imported/rocks.blend-98ef93dd145059a2bcdc7f8a6211eb83.scn. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://props/rocks/rocks.blend. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/resource_format_text.cpp:174 - res://props/rocks/rocks.tscn:14 - Parse Error: [ext_resource] referenced non-loaded resource at: res://props/rocks/rocks.blend
  scene/resources/packed_scene.cpp:178 - Node './rocks' was modified from inside an instance, but it has vanished.
...
```

The log continues and Godot will eventually enter into a loop, doing this:

![image](https://github.com/mikatomik/Godot-4-Overgrown-Subway-Demo/assets/853094/d937dfa1-9b52-4955-9ea5-57a2141c2be8)

...so, maybe a Godot bug.

Also wondering why you chose to commit the .godot folder to the repo.

**Comment by garyritchie** [comment]
I've also tried 3.3.4 and 3.4.1.

May be related to https://github.com/godotengine/godot/issues/67275

**Comment by mikatomik** [comment]
I am assuming this is a Godot bug, as I've had the looping on import happen to me on other projects a couple of times on a machine I have that has an older blender version on it. 

Also, I am using the .gitignore template that was provided by the documentation. If there is something wrong then I must have made a mistake somewhere. Im not exactly a Git guru, just wanted to share a project I was making.

**Comment by garyritchie** [comment]
Yes you are, sorry -- I wasn't thinking straight when leaving that comment. The history is still there (a78c406) in the repo, which explains the clone size. This explains a fix: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

I'll try to take a gander on a Windows machine I have.

**Comment by mikatomik** [comment]
Thanks for the tip, I will look into it this week. I'm also sorry for the inconvenience, as when I submitted to the Godot asset library I had to specify a commit for download and assumed the junk that I left in previous commits would not matter since it was removed in the commit I was submitting. 

Again, I have not spent much time with Git, so this whole thing has been a learning experience for me. The mistake happened when I first tried to clone the repo back to my machine and everything loaded up black. I thought I had excluded something I needed, so I removed the gitignore altogether, and it loaded up correctly. 

Then the asset library said I needed a gitignore or I would be rejected, it was then I found the template and used that. So clearly I had put something in my first gitignore that didn't need to be there.

So yes I made quite the mess trying to figure all this out. 🤣 

For what it's worth, on my main machine I use Blender 3.4 and haven't encountered the import loop (yet) with that. It's my older machine that has done that to me, and I can't recall exactly what version of Blender is on that right now but I know it's older than 3.4

**Comment by garyritchie** [comment]
No apology necessary. I'm pretty much a Godot newbie.

When introducing new applications to my workflow I do a search for "<application name> .gitignore" and "<application name> .gitattributes". These will also get added to my project template but it's impossible to avoid revising these files as a project progresses. 

IMHO making a mess is the best way to learn ;-). I'll admit Git makes it _easier_ to make a mess but it also removes the _stress_. Removes fear of losing work; makes a project portable; facilitates collaboration... and you can see how far you've come in a project. 

What OS are you using? The laptop I'll test on is Win11/Ubuntu 22.04.

**Comment by MartinHaeusler** [comment]
I'm also seeing this problem on Windows 10, Blender 3.5 and Godot 4.0.3 (mono).

Some *.blend files work fine out of the box, others just refuse to import at all.

The console window says this:
```
ERROR: Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
   at: append_from_file (modules/gltf/gltf_document.cpp:7431)
ERROR: Error importing 'res://grandLibrary_01.blend'.
   at: (editor/editor_file_system.cpp:2031)
ERROR: Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
   at: append_from_file (modules/gltf/gltf_document.cpp:7431)
ERROR: Error importing 'res://grandLibrary_01.blend'.
   at: (editor/editor_file_system.cpp:2031)
ERROR: Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
   at: append_from_file (modules/gltf/gltf_document.cpp:7431)
ERROR: Error importing 'res://grandLibrary_01.blend'.
   at: (editor/editor_file_system.cpp:2031)
ERROR: Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
   at: append_from_file (modules/gltf/gltf_document.cpp:7431)
ERROR: Error importing 'res://grandLibrary_01.blend'.
   at: (editor/editor_file_system.cpp:2031)
ERROR: No loader found for resource: res://grandLibrary_01.blend.
   at: (core/io/resource_loader.cpp:230)
ERROR: No loader found for resource: res://grandLibrary_01.blend.
   at: (core/io/resource_loader.cpp:230)
ERROR: No loader found for resource: res://grandLibrary_01.blend.
   at: (core/io/resource_loader.cpp:230)
ERROR: No loader found for resource: res://grandLibrary_01.blend.
   at: (core/io/resource_loader.cpp:230)
ERROR: No loader found for resource: res://grandLibrary_01.blend.
   at: (core/io/resource_loader.cpp:230)
ERROR: No loader found for resource: res://grandLibrary_01.blend.
   at: (core/io/resource_loader.cpp:230)
ERROR: No loader found for resource: res://grandLibrary_01.blend.
   at: (core/io/resource_loader.cpp:230)
ERROR: No loader found for resource: res://grandLibrary_01.blend.
   at: (core/io/resource_loader.cpp:230)
ERROR: No loader found for resource: res://grandLibrary_01.blend.
   at: (core/io/resource_loader.cpp:230)
ERROR: No loader found for resource: res://grandLibrary_01.blend.
   at: (core/io/resource_loader.cpp:230)
ERROR: No loader found for resource: res://grandLibrary_01.blend.
   at: (core/io/resource_loader.cpp:230)
ERROR: No loader found for resource: res://grandLibrary_01.blend.
   at: (core/io/resource_loader.cpp:230)
ERROR: Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
   at: append_from_file (modules/gltf/gltf_document.cpp:7431)
ERROR: Error importing 'res://grandLibrary_01.blend'.
   at: (editor/editor_file_system.cpp:2031)
```

Also, on a related note, the *.blend files seem to get reimported into Godot every time I de-focus and re-focus the godot window. This is extremely annoying because it takes a few seconds every time (and I only have two *.blend files in my project at the moment; I can imagine how it would feel with 100s of them...). Is this a known issue?

Also: in the Godot settings, the blender importer was enabled by default, but I had to manually disable it, re-enable it and restart godot in order to see any *.blend files at all being registered by the asset importer.
